// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IrrigationSystem.proto

// Protobuf Java Version: 3.25.1
package com.project;

public final class IrrigationSystemProto {
  private IrrigationSystemProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface IrrigationStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IrrigationStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string currentStatus = 1;</code>
     * @return The currentStatus.
     */
    java.lang.String getCurrentStatus();
    /**
     * <code>string currentStatus = 1;</code>
     * @return The bytes for currentStatus.
     */
    com.google.protobuf.ByteString
        getCurrentStatusBytes();

    /**
     * <code>int32 flowRate = 2;</code>
     * @return The flowRate.
     */
    int getFlowRate();
  }
  /**
   * Protobuf type {@code IrrigationStatus}
   */
  public static final class IrrigationStatus extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:IrrigationStatus)
      IrrigationStatusOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IrrigationStatus.newBuilder() to construct.
    private IrrigationStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IrrigationStatus() {
      currentStatus_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new IrrigationStatus();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.project.IrrigationSystemProto.internal_static_IrrigationStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.project.IrrigationSystemProto.internal_static_IrrigationStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.project.IrrigationSystemProto.IrrigationStatus.class, com.project.IrrigationSystemProto.IrrigationStatus.Builder.class);
    }

    public static final int CURRENTSTATUS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object currentStatus_ = "";
    /**
     * <code>string currentStatus = 1;</code>
     * @return The currentStatus.
     */
    @java.lang.Override
    public java.lang.String getCurrentStatus() {
      java.lang.Object ref = currentStatus_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currentStatus_ = s;
        return s;
      }
    }
    /**
     * <code>string currentStatus = 1;</code>
     * @return The bytes for currentStatus.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCurrentStatusBytes() {
      java.lang.Object ref = currentStatus_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currentStatus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FLOWRATE_FIELD_NUMBER = 2;
    private int flowRate_ = 0;
    /**
     * <code>int32 flowRate = 2;</code>
     * @return The flowRate.
     */
    @java.lang.Override
    public int getFlowRate() {
      return flowRate_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(currentStatus_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, currentStatus_);
      }
      if (flowRate_ != 0) {
        output.writeInt32(2, flowRate_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(currentStatus_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, currentStatus_);
      }
      if (flowRate_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, flowRate_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.project.IrrigationSystemProto.IrrigationStatus)) {
        return super.equals(obj);
      }
      com.project.IrrigationSystemProto.IrrigationStatus other = (com.project.IrrigationSystemProto.IrrigationStatus) obj;

      if (!getCurrentStatus()
          .equals(other.getCurrentStatus())) return false;
      if (getFlowRate()
          != other.getFlowRate()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CURRENTSTATUS_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentStatus().hashCode();
      hash = (37 * hash) + FLOWRATE_FIELD_NUMBER;
      hash = (53 * hash) + getFlowRate();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.project.IrrigationSystemProto.IrrigationStatus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.project.IrrigationSystemProto.IrrigationStatus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.project.IrrigationSystemProto.IrrigationStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.project.IrrigationSystemProto.IrrigationStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.project.IrrigationSystemProto.IrrigationStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.project.IrrigationSystemProto.IrrigationStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.project.IrrigationSystemProto.IrrigationStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.project.IrrigationSystemProto.IrrigationStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.project.IrrigationSystemProto.IrrigationStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.project.IrrigationSystemProto.IrrigationStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.project.IrrigationSystemProto.IrrigationStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.project.IrrigationSystemProto.IrrigationStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.project.IrrigationSystemProto.IrrigationStatus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code IrrigationStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:IrrigationStatus)
        com.project.IrrigationSystemProto.IrrigationStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.project.IrrigationSystemProto.internal_static_IrrigationStatus_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.project.IrrigationSystemProto.internal_static_IrrigationStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.project.IrrigationSystemProto.IrrigationStatus.class, com.project.IrrigationSystemProto.IrrigationStatus.Builder.class);
      }

      // Construct using com.project.IrrigationSystemProto.IrrigationStatus.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        currentStatus_ = "";
        flowRate_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.project.IrrigationSystemProto.internal_static_IrrigationStatus_descriptor;
      }

      @java.lang.Override
      public com.project.IrrigationSystemProto.IrrigationStatus getDefaultInstanceForType() {
        return com.project.IrrigationSystemProto.IrrigationStatus.getDefaultInstance();
      }

      @java.lang.Override
      public com.project.IrrigationSystemProto.IrrigationStatus build() {
        com.project.IrrigationSystemProto.IrrigationStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.project.IrrigationSystemProto.IrrigationStatus buildPartial() {
        com.project.IrrigationSystemProto.IrrigationStatus result = new com.project.IrrigationSystemProto.IrrigationStatus(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.project.IrrigationSystemProto.IrrigationStatus result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.currentStatus_ = currentStatus_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.flowRate_ = flowRate_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.project.IrrigationSystemProto.IrrigationStatus) {
          return mergeFrom((com.project.IrrigationSystemProto.IrrigationStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.project.IrrigationSystemProto.IrrigationStatus other) {
        if (other == com.project.IrrigationSystemProto.IrrigationStatus.getDefaultInstance()) return this;
        if (!other.getCurrentStatus().isEmpty()) {
          currentStatus_ = other.currentStatus_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getFlowRate() != 0) {
          setFlowRate(other.getFlowRate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                currentStatus_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                flowRate_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object currentStatus_ = "";
      /**
       * <code>string currentStatus = 1;</code>
       * @return The currentStatus.
       */
      public java.lang.String getCurrentStatus() {
        java.lang.Object ref = currentStatus_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          currentStatus_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string currentStatus = 1;</code>
       * @return The bytes for currentStatus.
       */
      public com.google.protobuf.ByteString
          getCurrentStatusBytes() {
        java.lang.Object ref = currentStatus_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          currentStatus_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string currentStatus = 1;</code>
       * @param value The currentStatus to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentStatus(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        currentStatus_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string currentStatus = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrentStatus() {
        currentStatus_ = getDefaultInstance().getCurrentStatus();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string currentStatus = 1;</code>
       * @param value The bytes for currentStatus to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        currentStatus_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int flowRate_ ;
      /**
       * <code>int32 flowRate = 2;</code>
       * @return The flowRate.
       */
      @java.lang.Override
      public int getFlowRate() {
        return flowRate_;
      }
      /**
       * <code>int32 flowRate = 2;</code>
       * @param value The flowRate to set.
       * @return This builder for chaining.
       */
      public Builder setFlowRate(int value) {

        flowRate_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 flowRate = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFlowRate() {
        bitField0_ = (bitField0_ & ~0x00000002);
        flowRate_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:IrrigationStatus)
    }

    // @@protoc_insertion_point(class_scope:IrrigationStatus)
    private static final com.project.IrrigationSystemProto.IrrigationStatus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.project.IrrigationSystemProto.IrrigationStatus();
    }

    public static com.project.IrrigationSystemProto.IrrigationStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IrrigationStatus>
        PARSER = new com.google.protobuf.AbstractParser<IrrigationStatus>() {
      @java.lang.Override
      public IrrigationStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<IrrigationStatus> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IrrigationStatus> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.project.IrrigationSystemProto.IrrigationStatus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ServerInstructionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ServerInstruction)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string instruction = 1;</code>
     * @return The instruction.
     */
    java.lang.String getInstruction();
    /**
     * <code>string instruction = 1;</code>
     * @return The bytes for instruction.
     */
    com.google.protobuf.ByteString
        getInstructionBytes();

    /**
     * <code>int32 flowRate = 2;</code>
     * @return The flowRate.
     */
    int getFlowRate();
  }
  /**
   * Protobuf type {@code ServerInstruction}
   */
  public static final class ServerInstruction extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ServerInstruction)
      ServerInstructionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ServerInstruction.newBuilder() to construct.
    private ServerInstruction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ServerInstruction() {
      instruction_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ServerInstruction();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.project.IrrigationSystemProto.internal_static_ServerInstruction_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.project.IrrigationSystemProto.internal_static_ServerInstruction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.project.IrrigationSystemProto.ServerInstruction.class, com.project.IrrigationSystemProto.ServerInstruction.Builder.class);
    }

    public static final int INSTRUCTION_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object instruction_ = "";
    /**
     * <code>string instruction = 1;</code>
     * @return The instruction.
     */
    @java.lang.Override
    public java.lang.String getInstruction() {
      java.lang.Object ref = instruction_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        instruction_ = s;
        return s;
      }
    }
    /**
     * <code>string instruction = 1;</code>
     * @return The bytes for instruction.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getInstructionBytes() {
      java.lang.Object ref = instruction_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        instruction_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FLOWRATE_FIELD_NUMBER = 2;
    private int flowRate_ = 0;
    /**
     * <code>int32 flowRate = 2;</code>
     * @return The flowRate.
     */
    @java.lang.Override
    public int getFlowRate() {
      return flowRate_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(instruction_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, instruction_);
      }
      if (flowRate_ != 0) {
        output.writeInt32(2, flowRate_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(instruction_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, instruction_);
      }
      if (flowRate_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, flowRate_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.project.IrrigationSystemProto.ServerInstruction)) {
        return super.equals(obj);
      }
      com.project.IrrigationSystemProto.ServerInstruction other = (com.project.IrrigationSystemProto.ServerInstruction) obj;

      if (!getInstruction()
          .equals(other.getInstruction())) return false;
      if (getFlowRate()
          != other.getFlowRate()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INSTRUCTION_FIELD_NUMBER;
      hash = (53 * hash) + getInstruction().hashCode();
      hash = (37 * hash) + FLOWRATE_FIELD_NUMBER;
      hash = (53 * hash) + getFlowRate();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.project.IrrigationSystemProto.ServerInstruction parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.project.IrrigationSystemProto.ServerInstruction parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.project.IrrigationSystemProto.ServerInstruction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.project.IrrigationSystemProto.ServerInstruction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.project.IrrigationSystemProto.ServerInstruction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.project.IrrigationSystemProto.ServerInstruction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.project.IrrigationSystemProto.ServerInstruction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.project.IrrigationSystemProto.ServerInstruction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.project.IrrigationSystemProto.ServerInstruction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.project.IrrigationSystemProto.ServerInstruction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.project.IrrigationSystemProto.ServerInstruction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.project.IrrigationSystemProto.ServerInstruction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.project.IrrigationSystemProto.ServerInstruction prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ServerInstruction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ServerInstruction)
        com.project.IrrigationSystemProto.ServerInstructionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.project.IrrigationSystemProto.internal_static_ServerInstruction_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.project.IrrigationSystemProto.internal_static_ServerInstruction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.project.IrrigationSystemProto.ServerInstruction.class, com.project.IrrigationSystemProto.ServerInstruction.Builder.class);
      }

      // Construct using com.project.IrrigationSystemProto.ServerInstruction.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        instruction_ = "";
        flowRate_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.project.IrrigationSystemProto.internal_static_ServerInstruction_descriptor;
      }

      @java.lang.Override
      public com.project.IrrigationSystemProto.ServerInstruction getDefaultInstanceForType() {
        return com.project.IrrigationSystemProto.ServerInstruction.getDefaultInstance();
      }

      @java.lang.Override
      public com.project.IrrigationSystemProto.ServerInstruction build() {
        com.project.IrrigationSystemProto.ServerInstruction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.project.IrrigationSystemProto.ServerInstruction buildPartial() {
        com.project.IrrigationSystemProto.ServerInstruction result = new com.project.IrrigationSystemProto.ServerInstruction(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.project.IrrigationSystemProto.ServerInstruction result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.instruction_ = instruction_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.flowRate_ = flowRate_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.project.IrrigationSystemProto.ServerInstruction) {
          return mergeFrom((com.project.IrrigationSystemProto.ServerInstruction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.project.IrrigationSystemProto.ServerInstruction other) {
        if (other == com.project.IrrigationSystemProto.ServerInstruction.getDefaultInstance()) return this;
        if (!other.getInstruction().isEmpty()) {
          instruction_ = other.instruction_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getFlowRate() != 0) {
          setFlowRate(other.getFlowRate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                instruction_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                flowRate_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object instruction_ = "";
      /**
       * <code>string instruction = 1;</code>
       * @return The instruction.
       */
      public java.lang.String getInstruction() {
        java.lang.Object ref = instruction_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          instruction_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string instruction = 1;</code>
       * @return The bytes for instruction.
       */
      public com.google.protobuf.ByteString
          getInstructionBytes() {
        java.lang.Object ref = instruction_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          instruction_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string instruction = 1;</code>
       * @param value The instruction to set.
       * @return This builder for chaining.
       */
      public Builder setInstruction(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        instruction_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string instruction = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearInstruction() {
        instruction_ = getDefaultInstance().getInstruction();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string instruction = 1;</code>
       * @param value The bytes for instruction to set.
       * @return This builder for chaining.
       */
      public Builder setInstructionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        instruction_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int flowRate_ ;
      /**
       * <code>int32 flowRate = 2;</code>
       * @return The flowRate.
       */
      @java.lang.Override
      public int getFlowRate() {
        return flowRate_;
      }
      /**
       * <code>int32 flowRate = 2;</code>
       * @param value The flowRate to set.
       * @return This builder for chaining.
       */
      public Builder setFlowRate(int value) {

        flowRate_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 flowRate = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFlowRate() {
        bitField0_ = (bitField0_ & ~0x00000002);
        flowRate_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ServerInstruction)
    }

    // @@protoc_insertion_point(class_scope:ServerInstruction)
    private static final com.project.IrrigationSystemProto.ServerInstruction DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.project.IrrigationSystemProto.ServerInstruction();
    }

    public static com.project.IrrigationSystemProto.ServerInstruction getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ServerInstruction>
        PARSER = new com.google.protobuf.AbstractParser<ServerInstruction>() {
      @java.lang.Override
      public ServerInstruction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ServerInstruction> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ServerInstruction> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.project.IrrigationSystemProto.ServerInstruction getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IrrigationStatus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IrrigationStatus_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServerInstruction_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ServerInstruction_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026IrrigationSystem.proto\";\n\020IrrigationSt" +
      "atus\022\025\n\rcurrentStatus\030\001 \001(\t\022\020\n\010flowRate\030" +
      "\002 \001(\005\":\n\021ServerInstruction\022\023\n\013instructio" +
      "n\030\001 \001(\t\022\020\n\010flowRate\030\002 \001(\0052b\n\027IrrigationS" +
      "ystemService\022G\n\030InstructIrrigationSystem" +
      "\022\021.IrrigationStatus\032\022.ServerInstruction\"" +
      "\000(\0010\001B&\n\013com.projectB\025IrrigationSystemPr" +
      "otoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_IrrigationStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_IrrigationStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IrrigationStatus_descriptor,
        new java.lang.String[] { "CurrentStatus", "FlowRate", });
    internal_static_ServerInstruction_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ServerInstruction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ServerInstruction_descriptor,
        new java.lang.String[] { "Instruction", "FlowRate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
