// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: irrigationSystem.proto

// Protobuf Java Version: 3.25.1
package com.project;

public final class IrrigationSystemProto {
  private IrrigationSystemProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface IrrigationStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IrrigationStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string currentStatus = 1;</code>
     * @return The currentStatus.
     */
    java.lang.String getCurrentStatus();
    /**
     * <code>string currentStatus = 1;</code>
     * @return The bytes for currentStatus.
     */
    com.google.protobuf.ByteString
        getCurrentStatusBytes();

    /**
     * <pre>
     * the current flow rate of the irrigationSystem
     * </pre>
     *
     * <code>int32 flowRate = 2;</code>
     * @return The flowRate.
     */
    int getFlowRate();
  }
  /**
   * Protobuf type {@code IrrigationStatus}
   */
  public static final class IrrigationStatus extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:IrrigationStatus)
      IrrigationStatusOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IrrigationStatus.newBuilder() to construct.
    private IrrigationStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IrrigationStatus() {
      currentStatus_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new IrrigationStatus();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.project.IrrigationSystemProto.internal_static_IrrigationStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.project.IrrigationSystemProto.internal_static_IrrigationStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.project.IrrigationSystemProto.IrrigationStatus.class, com.project.IrrigationSystemProto.IrrigationStatus.Builder.class);
    }

    public static final int CURRENTSTATUS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object currentStatus_ = "";
    /**
     * <code>string currentStatus = 1;</code>
     * @return The currentStatus.
     */
    @java.lang.Override
    public java.lang.String getCurrentStatus() {
      java.lang.Object ref = currentStatus_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currentStatus_ = s;
        return s;
      }
    }
    /**
     * <code>string currentStatus = 1;</code>
     * @return The bytes for currentStatus.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCurrentStatusBytes() {
      java.lang.Object ref = currentStatus_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currentStatus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FLOWRATE_FIELD_NUMBER = 2;
    private int flowRate_ = 0;
    /**
     * <pre>
     * the current flow rate of the irrigationSystem
     * </pre>
     *
     * <code>int32 flowRate = 2;</code>
     * @return The flowRate.
     */
    @java.lang.Override
    public int getFlowRate() {
      return flowRate_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(currentStatus_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, currentStatus_);
      }
      if (flowRate_ != 0) {
        output.writeInt32(2, flowRate_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(currentStatus_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, currentStatus_);
      }
      if (flowRate_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, flowRate_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.project.IrrigationSystemProto.IrrigationStatus)) {
        return super.equals(obj);
      }
      com.project.IrrigationSystemProto.IrrigationStatus other = (com.project.IrrigationSystemProto.IrrigationStatus) obj;

      if (!getCurrentStatus()
          .equals(other.getCurrentStatus())) return false;
      if (getFlowRate()
          != other.getFlowRate()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CURRENTSTATUS_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentStatus().hashCode();
      hash = (37 * hash) + FLOWRATE_FIELD_NUMBER;
      hash = (53 * hash) + getFlowRate();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.project.IrrigationSystemProto.IrrigationStatus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.project.IrrigationSystemProto.IrrigationStatus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.project.IrrigationSystemProto.IrrigationStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.project.IrrigationSystemProto.IrrigationStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.project.IrrigationSystemProto.IrrigationStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.project.IrrigationSystemProto.IrrigationStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.project.IrrigationSystemProto.IrrigationStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.project.IrrigationSystemProto.IrrigationStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.project.IrrigationSystemProto.IrrigationStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.project.IrrigationSystemProto.IrrigationStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.project.IrrigationSystemProto.IrrigationStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.project.IrrigationSystemProto.IrrigationStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.project.IrrigationSystemProto.IrrigationStatus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code IrrigationStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:IrrigationStatus)
        com.project.IrrigationSystemProto.IrrigationStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.project.IrrigationSystemProto.internal_static_IrrigationStatus_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.project.IrrigationSystemProto.internal_static_IrrigationStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.project.IrrigationSystemProto.IrrigationStatus.class, com.project.IrrigationSystemProto.IrrigationStatus.Builder.class);
      }

      // Construct using com.project.IrrigationSystemProto.IrrigationStatus.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        currentStatus_ = "";
        flowRate_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.project.IrrigationSystemProto.internal_static_IrrigationStatus_descriptor;
      }

      @java.lang.Override
      public com.project.IrrigationSystemProto.IrrigationStatus getDefaultInstanceForType() {
        return com.project.IrrigationSystemProto.IrrigationStatus.getDefaultInstance();
      }

      @java.lang.Override
      public com.project.IrrigationSystemProto.IrrigationStatus build() {
        com.project.IrrigationSystemProto.IrrigationStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.project.IrrigationSystemProto.IrrigationStatus buildPartial() {
        com.project.IrrigationSystemProto.IrrigationStatus result = new com.project.IrrigationSystemProto.IrrigationStatus(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.project.IrrigationSystemProto.IrrigationStatus result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.currentStatus_ = currentStatus_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.flowRate_ = flowRate_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.project.IrrigationSystemProto.IrrigationStatus) {
          return mergeFrom((com.project.IrrigationSystemProto.IrrigationStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.project.IrrigationSystemProto.IrrigationStatus other) {
        if (other == com.project.IrrigationSystemProto.IrrigationStatus.getDefaultInstance()) return this;
        if (!other.getCurrentStatus().isEmpty()) {
          currentStatus_ = other.currentStatus_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getFlowRate() != 0) {
          setFlowRate(other.getFlowRate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                currentStatus_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                flowRate_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object currentStatus_ = "";
      /**
       * <code>string currentStatus = 1;</code>
       * @return The currentStatus.
       */
      public java.lang.String getCurrentStatus() {
        java.lang.Object ref = currentStatus_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          currentStatus_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string currentStatus = 1;</code>
       * @return The bytes for currentStatus.
       */
      public com.google.protobuf.ByteString
          getCurrentStatusBytes() {
        java.lang.Object ref = currentStatus_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          currentStatus_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string currentStatus = 1;</code>
       * @param value The currentStatus to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentStatus(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        currentStatus_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string currentStatus = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrentStatus() {
        currentStatus_ = getDefaultInstance().getCurrentStatus();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string currentStatus = 1;</code>
       * @param value The bytes for currentStatus to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        currentStatus_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int flowRate_ ;
      /**
       * <pre>
       * the current flow rate of the irrigationSystem
       * </pre>
       *
       * <code>int32 flowRate = 2;</code>
       * @return The flowRate.
       */
      @java.lang.Override
      public int getFlowRate() {
        return flowRate_;
      }
      /**
       * <pre>
       * the current flow rate of the irrigationSystem
       * </pre>
       *
       * <code>int32 flowRate = 2;</code>
       * @param value The flowRate to set.
       * @return This builder for chaining.
       */
      public Builder setFlowRate(int value) {

        flowRate_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the current flow rate of the irrigationSystem
       * </pre>
       *
       * <code>int32 flowRate = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFlowRate() {
        bitField0_ = (bitField0_ & ~0x00000002);
        flowRate_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:IrrigationStatus)
    }

    // @@protoc_insertion_point(class_scope:IrrigationStatus)
    private static final com.project.IrrigationSystemProto.IrrigationStatus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.project.IrrigationSystemProto.IrrigationStatus();
    }

    public static com.project.IrrigationSystemProto.IrrigationStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IrrigationStatus>
        PARSER = new com.google.protobuf.AbstractParser<IrrigationStatus>() {
      @java.lang.Override
      public IrrigationStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<IrrigationStatus> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IrrigationStatus> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.project.IrrigationSystemProto.IrrigationStatus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ServerInstructionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ServerInstruction)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * instruction to turn on or off of the IrrigationSystem
     * </pre>
     *
     * <code>string instruction = 1;</code>
     * @return The instruction.
     */
    java.lang.String getInstruction();
    /**
     * <pre>
     * instruction to turn on or off of the IrrigationSystem
     * </pre>
     *
     * <code>string instruction = 1;</code>
     * @return The bytes for instruction.
     */
    com.google.protobuf.ByteString
        getInstructionBytes();

    /**
     * <pre>
     * instruction to set the flow rate of the IrrigationSystem
     * </pre>
     *
     * <code>int32 flowRate = 2;</code>
     * @return The flowRate.
     */
    int getFlowRate();
  }
  /**
   * Protobuf type {@code ServerInstruction}
   */
  public static final class ServerInstruction extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ServerInstruction)
      ServerInstructionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ServerInstruction.newBuilder() to construct.
    private ServerInstruction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ServerInstruction() {
      instruction_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ServerInstruction();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.project.IrrigationSystemProto.internal_static_ServerInstruction_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.project.IrrigationSystemProto.internal_static_ServerInstruction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.project.IrrigationSystemProto.ServerInstruction.class, com.project.IrrigationSystemProto.ServerInstruction.Builder.class);
    }

    public static final int INSTRUCTION_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object instruction_ = "";
    /**
     * <pre>
     * instruction to turn on or off of the IrrigationSystem
     * </pre>
     *
     * <code>string instruction = 1;</code>
     * @return The instruction.
     */
    @java.lang.Override
    public java.lang.String getInstruction() {
      java.lang.Object ref = instruction_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        instruction_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * instruction to turn on or off of the IrrigationSystem
     * </pre>
     *
     * <code>string instruction = 1;</code>
     * @return The bytes for instruction.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getInstructionBytes() {
      java.lang.Object ref = instruction_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        instruction_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FLOWRATE_FIELD_NUMBER = 2;
    private int flowRate_ = 0;
    /**
     * <pre>
     * instruction to set the flow rate of the IrrigationSystem
     * </pre>
     *
     * <code>int32 flowRate = 2;</code>
     * @return The flowRate.
     */
    @java.lang.Override
    public int getFlowRate() {
      return flowRate_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(instruction_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, instruction_);
      }
      if (flowRate_ != 0) {
        output.writeInt32(2, flowRate_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(instruction_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, instruction_);
      }
      if (flowRate_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, flowRate_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.project.IrrigationSystemProto.ServerInstruction)) {
        return super.equals(obj);
      }
      com.project.IrrigationSystemProto.ServerInstruction other = (com.project.IrrigationSystemProto.ServerInstruction) obj;

      if (!getInstruction()
          .equals(other.getInstruction())) return false;
      if (getFlowRate()
          != other.getFlowRate()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INSTRUCTION_FIELD_NUMBER;
      hash = (53 * hash) + getInstruction().hashCode();
      hash = (37 * hash) + FLOWRATE_FIELD_NUMBER;
      hash = (53 * hash) + getFlowRate();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.project.IrrigationSystemProto.ServerInstruction parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.project.IrrigationSystemProto.ServerInstruction parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.project.IrrigationSystemProto.ServerInstruction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.project.IrrigationSystemProto.ServerInstruction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.project.IrrigationSystemProto.ServerInstruction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.project.IrrigationSystemProto.ServerInstruction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.project.IrrigationSystemProto.ServerInstruction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.project.IrrigationSystemProto.ServerInstruction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.project.IrrigationSystemProto.ServerInstruction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.project.IrrigationSystemProto.ServerInstruction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.project.IrrigationSystemProto.ServerInstruction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.project.IrrigationSystemProto.ServerInstruction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.project.IrrigationSystemProto.ServerInstruction prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ServerInstruction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ServerInstruction)
        com.project.IrrigationSystemProto.ServerInstructionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.project.IrrigationSystemProto.internal_static_ServerInstruction_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.project.IrrigationSystemProto.internal_static_ServerInstruction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.project.IrrigationSystemProto.ServerInstruction.class, com.project.IrrigationSystemProto.ServerInstruction.Builder.class);
      }

      // Construct using com.project.IrrigationSystemProto.ServerInstruction.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        instruction_ = "";
        flowRate_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.project.IrrigationSystemProto.internal_static_ServerInstruction_descriptor;
      }

      @java.lang.Override
      public com.project.IrrigationSystemProto.ServerInstruction getDefaultInstanceForType() {
        return com.project.IrrigationSystemProto.ServerInstruction.getDefaultInstance();
      }

      @java.lang.Override
      public com.project.IrrigationSystemProto.ServerInstruction build() {
        com.project.IrrigationSystemProto.ServerInstruction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.project.IrrigationSystemProto.ServerInstruction buildPartial() {
        com.project.IrrigationSystemProto.ServerInstruction result = new com.project.IrrigationSystemProto.ServerInstruction(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.project.IrrigationSystemProto.ServerInstruction result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.instruction_ = instruction_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.flowRate_ = flowRate_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.project.IrrigationSystemProto.ServerInstruction) {
          return mergeFrom((com.project.IrrigationSystemProto.ServerInstruction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.project.IrrigationSystemProto.ServerInstruction other) {
        if (other == com.project.IrrigationSystemProto.ServerInstruction.getDefaultInstance()) return this;
        if (!other.getInstruction().isEmpty()) {
          instruction_ = other.instruction_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getFlowRate() != 0) {
          setFlowRate(other.getFlowRate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                instruction_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                flowRate_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object instruction_ = "";
      /**
       * <pre>
       * instruction to turn on or off of the IrrigationSystem
       * </pre>
       *
       * <code>string instruction = 1;</code>
       * @return The instruction.
       */
      public java.lang.String getInstruction() {
        java.lang.Object ref = instruction_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          instruction_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * instruction to turn on or off of the IrrigationSystem
       * </pre>
       *
       * <code>string instruction = 1;</code>
       * @return The bytes for instruction.
       */
      public com.google.protobuf.ByteString
          getInstructionBytes() {
        java.lang.Object ref = instruction_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          instruction_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * instruction to turn on or off of the IrrigationSystem
       * </pre>
       *
       * <code>string instruction = 1;</code>
       * @param value The instruction to set.
       * @return This builder for chaining.
       */
      public Builder setInstruction(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        instruction_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * instruction to turn on or off of the IrrigationSystem
       * </pre>
       *
       * <code>string instruction = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearInstruction() {
        instruction_ = getDefaultInstance().getInstruction();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * instruction to turn on or off of the IrrigationSystem
       * </pre>
       *
       * <code>string instruction = 1;</code>
       * @param value The bytes for instruction to set.
       * @return This builder for chaining.
       */
      public Builder setInstructionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        instruction_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int flowRate_ ;
      /**
       * <pre>
       * instruction to set the flow rate of the IrrigationSystem
       * </pre>
       *
       * <code>int32 flowRate = 2;</code>
       * @return The flowRate.
       */
      @java.lang.Override
      public int getFlowRate() {
        return flowRate_;
      }
      /**
       * <pre>
       * instruction to set the flow rate of the IrrigationSystem
       * </pre>
       *
       * <code>int32 flowRate = 2;</code>
       * @param value The flowRate to set.
       * @return This builder for chaining.
       */
      public Builder setFlowRate(int value) {

        flowRate_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * instruction to set the flow rate of the IrrigationSystem
       * </pre>
       *
       * <code>int32 flowRate = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFlowRate() {
        bitField0_ = (bitField0_ & ~0x00000002);
        flowRate_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ServerInstruction)
    }

    // @@protoc_insertion_point(class_scope:ServerInstruction)
    private static final com.project.IrrigationSystemProto.ServerInstruction DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.project.IrrigationSystemProto.ServerInstruction();
    }

    public static com.project.IrrigationSystemProto.ServerInstruction getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ServerInstruction>
        PARSER = new com.google.protobuf.AbstractParser<ServerInstruction>() {
      @java.lang.Override
      public ServerInstruction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ServerInstruction> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ServerInstruction> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.project.IrrigationSystemProto.ServerInstruction getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HealthCheckRequest1OrBuilder extends
      // @@protoc_insertion_point(interface_extends:HealthCheckRequest1)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string serviceName = 1;</code>
     * @return The serviceName.
     */
    java.lang.String getServiceName();
    /**
     * <code>string serviceName = 1;</code>
     * @return The bytes for serviceName.
     */
    com.google.protobuf.ByteString
        getServiceNameBytes();

    /**
     * <code>string serviceVersion = 2;</code>
     * @return The serviceVersion.
     */
    java.lang.String getServiceVersion();
    /**
     * <code>string serviceVersion = 2;</code>
     * @return The bytes for serviceVersion.
     */
    com.google.protobuf.ByteString
        getServiceVersionBytes();

    /**
     * <code>int64 timestamp = 3;</code>
     * @return The timestamp.
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code HealthCheckRequest1}
   */
  public static final class HealthCheckRequest1 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HealthCheckRequest1)
      HealthCheckRequest1OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HealthCheckRequest1.newBuilder() to construct.
    private HealthCheckRequest1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HealthCheckRequest1() {
      serviceName_ = "";
      serviceVersion_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HealthCheckRequest1();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.project.IrrigationSystemProto.internal_static_HealthCheckRequest1_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.project.IrrigationSystemProto.internal_static_HealthCheckRequest1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.project.IrrigationSystemProto.HealthCheckRequest1.class, com.project.IrrigationSystemProto.HealthCheckRequest1.Builder.class);
    }

    public static final int SERVICENAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object serviceName_ = "";
    /**
     * <code>string serviceName = 1;</code>
     * @return The serviceName.
     */
    @java.lang.Override
    public java.lang.String getServiceName() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serviceName_ = s;
        return s;
      }
    }
    /**
     * <code>string serviceName = 1;</code>
     * @return The bytes for serviceName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getServiceNameBytes() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVICEVERSION_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object serviceVersion_ = "";
    /**
     * <code>string serviceVersion = 2;</code>
     * @return The serviceVersion.
     */
    @java.lang.Override
    public java.lang.String getServiceVersion() {
      java.lang.Object ref = serviceVersion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serviceVersion_ = s;
        return s;
      }
    }
    /**
     * <code>string serviceVersion = 2;</code>
     * @return The bytes for serviceVersion.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getServiceVersionBytes() {
      java.lang.Object ref = serviceVersion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private long timestamp_ = 0L;
    /**
     * <code>int64 timestamp = 3;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serviceName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, serviceName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serviceVersion_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, serviceVersion_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(3, timestamp_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serviceName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, serviceName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serviceVersion_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, serviceVersion_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, timestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.project.IrrigationSystemProto.HealthCheckRequest1)) {
        return super.equals(obj);
      }
      com.project.IrrigationSystemProto.HealthCheckRequest1 other = (com.project.IrrigationSystemProto.HealthCheckRequest1) obj;

      if (!getServiceName()
          .equals(other.getServiceName())) return false;
      if (!getServiceVersion()
          .equals(other.getServiceVersion())) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SERVICENAME_FIELD_NUMBER;
      hash = (53 * hash) + getServiceName().hashCode();
      hash = (37 * hash) + SERVICEVERSION_FIELD_NUMBER;
      hash = (53 * hash) + getServiceVersion().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.project.IrrigationSystemProto.HealthCheckRequest1 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.project.IrrigationSystemProto.HealthCheckRequest1 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.project.IrrigationSystemProto.HealthCheckRequest1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.project.IrrigationSystemProto.HealthCheckRequest1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.project.IrrigationSystemProto.HealthCheckRequest1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.project.IrrigationSystemProto.HealthCheckRequest1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.project.IrrigationSystemProto.HealthCheckRequest1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.project.IrrigationSystemProto.HealthCheckRequest1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.project.IrrigationSystemProto.HealthCheckRequest1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.project.IrrigationSystemProto.HealthCheckRequest1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.project.IrrigationSystemProto.HealthCheckRequest1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.project.IrrigationSystemProto.HealthCheckRequest1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.project.IrrigationSystemProto.HealthCheckRequest1 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HealthCheckRequest1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HealthCheckRequest1)
        com.project.IrrigationSystemProto.HealthCheckRequest1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.project.IrrigationSystemProto.internal_static_HealthCheckRequest1_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.project.IrrigationSystemProto.internal_static_HealthCheckRequest1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.project.IrrigationSystemProto.HealthCheckRequest1.class, com.project.IrrigationSystemProto.HealthCheckRequest1.Builder.class);
      }

      // Construct using com.project.IrrigationSystemProto.HealthCheckRequest1.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        serviceName_ = "";
        serviceVersion_ = "";
        timestamp_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.project.IrrigationSystemProto.internal_static_HealthCheckRequest1_descriptor;
      }

      @java.lang.Override
      public com.project.IrrigationSystemProto.HealthCheckRequest1 getDefaultInstanceForType() {
        return com.project.IrrigationSystemProto.HealthCheckRequest1.getDefaultInstance();
      }

      @java.lang.Override
      public com.project.IrrigationSystemProto.HealthCheckRequest1 build() {
        com.project.IrrigationSystemProto.HealthCheckRequest1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.project.IrrigationSystemProto.HealthCheckRequest1 buildPartial() {
        com.project.IrrigationSystemProto.HealthCheckRequest1 result = new com.project.IrrigationSystemProto.HealthCheckRequest1(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.project.IrrigationSystemProto.HealthCheckRequest1 result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.serviceName_ = serviceName_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.serviceVersion_ = serviceVersion_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.timestamp_ = timestamp_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.project.IrrigationSystemProto.HealthCheckRequest1) {
          return mergeFrom((com.project.IrrigationSystemProto.HealthCheckRequest1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.project.IrrigationSystemProto.HealthCheckRequest1 other) {
        if (other == com.project.IrrigationSystemProto.HealthCheckRequest1.getDefaultInstance()) return this;
        if (!other.getServiceName().isEmpty()) {
          serviceName_ = other.serviceName_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getServiceVersion().isEmpty()) {
          serviceVersion_ = other.serviceVersion_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                serviceName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                serviceVersion_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                timestamp_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object serviceName_ = "";
      /**
       * <code>string serviceName = 1;</code>
       * @return The serviceName.
       */
      public java.lang.String getServiceName() {
        java.lang.Object ref = serviceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          serviceName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string serviceName = 1;</code>
       * @return The bytes for serviceName.
       */
      public com.google.protobuf.ByteString
          getServiceNameBytes() {
        java.lang.Object ref = serviceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serviceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string serviceName = 1;</code>
       * @param value The serviceName to set.
       * @return This builder for chaining.
       */
      public Builder setServiceName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        serviceName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string serviceName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearServiceName() {
        serviceName_ = getDefaultInstance().getServiceName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string serviceName = 1;</code>
       * @param value The bytes for serviceName to set.
       * @return This builder for chaining.
       */
      public Builder setServiceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        serviceName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object serviceVersion_ = "";
      /**
       * <code>string serviceVersion = 2;</code>
       * @return The serviceVersion.
       */
      public java.lang.String getServiceVersion() {
        java.lang.Object ref = serviceVersion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          serviceVersion_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string serviceVersion = 2;</code>
       * @return The bytes for serviceVersion.
       */
      public com.google.protobuf.ByteString
          getServiceVersionBytes() {
        java.lang.Object ref = serviceVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serviceVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string serviceVersion = 2;</code>
       * @param value The serviceVersion to set.
       * @return This builder for chaining.
       */
      public Builder setServiceVersion(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        serviceVersion_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string serviceVersion = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearServiceVersion() {
        serviceVersion_ = getDefaultInstance().getServiceVersion();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string serviceVersion = 2;</code>
       * @param value The bytes for serviceVersion to set.
       * @return This builder for chaining.
       */
      public Builder setServiceVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        serviceVersion_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 3;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 3;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {

        timestamp_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HealthCheckRequest1)
    }

    // @@protoc_insertion_point(class_scope:HealthCheckRequest1)
    private static final com.project.IrrigationSystemProto.HealthCheckRequest1 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.project.IrrigationSystemProto.HealthCheckRequest1();
    }

    public static com.project.IrrigationSystemProto.HealthCheckRequest1 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HealthCheckRequest1>
        PARSER = new com.google.protobuf.AbstractParser<HealthCheckRequest1>() {
      @java.lang.Override
      public HealthCheckRequest1 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<HealthCheckRequest1> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HealthCheckRequest1> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.project.IrrigationSystemProto.HealthCheckRequest1 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HealthCheckResponse1OrBuilder extends
      // @@protoc_insertion_point(interface_extends:HealthCheckResponse1)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 status = 1;</code>
     * @return The status.
     */
    int getStatus();

    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code HealthCheckResponse1}
   */
  public static final class HealthCheckResponse1 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HealthCheckResponse1)
      HealthCheckResponse1OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HealthCheckResponse1.newBuilder() to construct.
    private HealthCheckResponse1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HealthCheckResponse1() {
      message_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HealthCheckResponse1();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.project.IrrigationSystemProto.internal_static_HealthCheckResponse1_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.project.IrrigationSystemProto.internal_static_HealthCheckResponse1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.project.IrrigationSystemProto.HealthCheckResponse1.class, com.project.IrrigationSystemProto.HealthCheckResponse1.Builder.class);
    }

    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_ = 0;
    /**
     * <code>int32 status = 1;</code>
     * @return The status.
     */
    @java.lang.Override
    public int getStatus() {
      return status_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object message_ = "";
    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (status_ != 0) {
        output.writeInt32(1, status_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, status_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.project.IrrigationSystemProto.HealthCheckResponse1)) {
        return super.equals(obj);
      }
      com.project.IrrigationSystemProto.HealthCheckResponse1 other = (com.project.IrrigationSystemProto.HealthCheckResponse1) obj;

      if (getStatus()
          != other.getStatus()) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.project.IrrigationSystemProto.HealthCheckResponse1 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.project.IrrigationSystemProto.HealthCheckResponse1 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.project.IrrigationSystemProto.HealthCheckResponse1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.project.IrrigationSystemProto.HealthCheckResponse1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.project.IrrigationSystemProto.HealthCheckResponse1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.project.IrrigationSystemProto.HealthCheckResponse1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.project.IrrigationSystemProto.HealthCheckResponse1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.project.IrrigationSystemProto.HealthCheckResponse1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.project.IrrigationSystemProto.HealthCheckResponse1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.project.IrrigationSystemProto.HealthCheckResponse1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.project.IrrigationSystemProto.HealthCheckResponse1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.project.IrrigationSystemProto.HealthCheckResponse1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.project.IrrigationSystemProto.HealthCheckResponse1 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HealthCheckResponse1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HealthCheckResponse1)
        com.project.IrrigationSystemProto.HealthCheckResponse1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.project.IrrigationSystemProto.internal_static_HealthCheckResponse1_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.project.IrrigationSystemProto.internal_static_HealthCheckResponse1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.project.IrrigationSystemProto.HealthCheckResponse1.class, com.project.IrrigationSystemProto.HealthCheckResponse1.Builder.class);
      }

      // Construct using com.project.IrrigationSystemProto.HealthCheckResponse1.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        status_ = 0;
        message_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.project.IrrigationSystemProto.internal_static_HealthCheckResponse1_descriptor;
      }

      @java.lang.Override
      public com.project.IrrigationSystemProto.HealthCheckResponse1 getDefaultInstanceForType() {
        return com.project.IrrigationSystemProto.HealthCheckResponse1.getDefaultInstance();
      }

      @java.lang.Override
      public com.project.IrrigationSystemProto.HealthCheckResponse1 build() {
        com.project.IrrigationSystemProto.HealthCheckResponse1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.project.IrrigationSystemProto.HealthCheckResponse1 buildPartial() {
        com.project.IrrigationSystemProto.HealthCheckResponse1 result = new com.project.IrrigationSystemProto.HealthCheckResponse1(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.project.IrrigationSystemProto.HealthCheckResponse1 result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.status_ = status_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.message_ = message_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.project.IrrigationSystemProto.HealthCheckResponse1) {
          return mergeFrom((com.project.IrrigationSystemProto.HealthCheckResponse1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.project.IrrigationSystemProto.HealthCheckResponse1 other) {
        if (other == com.project.IrrigationSystemProto.HealthCheckResponse1.getDefaultInstance()) return this;
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                status_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                message_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int status_ ;
      /**
       * <code>int32 status = 1;</code>
       * @return The status.
       */
      @java.lang.Override
      public int getStatus() {
        return status_;
      }
      /**
       * <code>int32 status = 1;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(int value) {

        status_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 status = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 2;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        message_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        message_ = getDefaultInstance().getMessage();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        message_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HealthCheckResponse1)
    }

    // @@protoc_insertion_point(class_scope:HealthCheckResponse1)
    private static final com.project.IrrigationSystemProto.HealthCheckResponse1 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.project.IrrigationSystemProto.HealthCheckResponse1();
    }

    public static com.project.IrrigationSystemProto.HealthCheckResponse1 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HealthCheckResponse1>
        PARSER = new com.google.protobuf.AbstractParser<HealthCheckResponse1>() {
      @java.lang.Override
      public HealthCheckResponse1 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<HealthCheckResponse1> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HealthCheckResponse1> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.project.IrrigationSystemProto.HealthCheckResponse1 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IrrigationStatus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IrrigationStatus_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServerInstruction_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ServerInstruction_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HealthCheckRequest1_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HealthCheckRequest1_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HealthCheckResponse1_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HealthCheckResponse1_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026irrigationSystem.proto\";\n\020IrrigationSt" +
      "atus\022\025\n\rcurrentStatus\030\001 \001(\t\022\020\n\010flowRate\030" +
      "\002 \001(\005\":\n\021ServerInstruction\022\023\n\013instructio" +
      "n\030\001 \001(\t\022\020\n\010flowRate\030\002 \001(\005\"U\n\023HealthCheck" +
      "Request1\022\023\n\013serviceName\030\001 \001(\t\022\026\n\016service" +
      "Version\030\002 \001(\t\022\021\n\ttimestamp\030\003 \001(\003\"7\n\024Heal" +
      "thCheckResponse1\022\016\n\006status\030\001 \001(\005\022\017\n\007mess" +
      "age\030\002 \001(\t2\237\001\n\027IrrigationSystemService\022E\n" +
      "\030InstructIrrigationSystem\022\021.IrrigationSt" +
      "atus\032\022.ServerInstruction(\0010\001\022=\n\014HealthCh" +
      "eck1\022\024.HealthCheckRequest1\032\025.HealthCheck" +
      "Response10\001B&\n\013com.projectB\025IrrigationSy" +
      "stemProtoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_IrrigationStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_IrrigationStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IrrigationStatus_descriptor,
        new java.lang.String[] { "CurrentStatus", "FlowRate", });
    internal_static_ServerInstruction_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ServerInstruction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ServerInstruction_descriptor,
        new java.lang.String[] { "Instruction", "FlowRate", });
    internal_static_HealthCheckRequest1_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_HealthCheckRequest1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HealthCheckRequest1_descriptor,
        new java.lang.String[] { "ServiceName", "ServiceVersion", "Timestamp", });
    internal_static_HealthCheckResponse1_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_HealthCheckResponse1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HealthCheckResponse1_descriptor,
        new java.lang.String[] { "Status", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
