// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IrrigationSystem.proto

// Protobuf Java Version: 3.25.1
package com.project;

public final class IrrigationSystemProto {
  private IrrigationSystemProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface IrrigationSystemRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IrrigationSystemRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Soil moisture level: 'Very Low Level', 'Low Level', 'Optimal Level', or 'High Level'.
     * </pre>
     *
     * <code>string soilMoisture = 1;</code>
     * @return The soilMoisture.
     */
    java.lang.String getSoilMoisture();
    /**
     * <pre>
     * Soil moisture level: 'Very Low Level', 'Low Level', 'Optimal Level', or 'High Level'.
     * </pre>
     *
     * <code>string soilMoisture = 1;</code>
     * @return The bytes for soilMoisture.
     */
    com.google.protobuf.ByteString
        getSoilMoistureBytes();

    /**
     * <pre>
     * Water flow rate: 'Low Flow', or 'High Flow'.
     * </pre>
     *
     * <code>string flowRate = 2;</code>
     * @return The flowRate.
     */
    java.lang.String getFlowRate();
    /**
     * <pre>
     * Water flow rate: 'Low Flow', or 'High Flow'.
     * </pre>
     *
     * <code>string flowRate = 2;</code>
     * @return The bytes for flowRate.
     */
    com.google.protobuf.ByteString
        getFlowRateBytes();
  }
  /**
   * Protobuf type {@code IrrigationSystemRequest}
   */
  public static final class IrrigationSystemRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:IrrigationSystemRequest)
      IrrigationSystemRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IrrigationSystemRequest.newBuilder() to construct.
    private IrrigationSystemRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IrrigationSystemRequest() {
      soilMoisture_ = "";
      flowRate_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new IrrigationSystemRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.project.IrrigationSystemProto.internal_static_IrrigationSystemRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.project.IrrigationSystemProto.internal_static_IrrigationSystemRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.project.IrrigationSystemProto.IrrigationSystemRequest.class, com.project.IrrigationSystemProto.IrrigationSystemRequest.Builder.class);
    }

    public static final int SOILMOISTURE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object soilMoisture_ = "";
    /**
     * <pre>
     * Soil moisture level: 'Very Low Level', 'Low Level', 'Optimal Level', or 'High Level'.
     * </pre>
     *
     * <code>string soilMoisture = 1;</code>
     * @return The soilMoisture.
     */
    @java.lang.Override
    public java.lang.String getSoilMoisture() {
      java.lang.Object ref = soilMoisture_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        soilMoisture_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Soil moisture level: 'Very Low Level', 'Low Level', 'Optimal Level', or 'High Level'.
     * </pre>
     *
     * <code>string soilMoisture = 1;</code>
     * @return The bytes for soilMoisture.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSoilMoistureBytes() {
      java.lang.Object ref = soilMoisture_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        soilMoisture_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FLOWRATE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object flowRate_ = "";
    /**
     * <pre>
     * Water flow rate: 'Low Flow', or 'High Flow'.
     * </pre>
     *
     * <code>string flowRate = 2;</code>
     * @return The flowRate.
     */
    @java.lang.Override
    public java.lang.String getFlowRate() {
      java.lang.Object ref = flowRate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        flowRate_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Water flow rate: 'Low Flow', or 'High Flow'.
     * </pre>
     *
     * <code>string flowRate = 2;</code>
     * @return The bytes for flowRate.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFlowRateBytes() {
      java.lang.Object ref = flowRate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        flowRate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(soilMoisture_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, soilMoisture_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(flowRate_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, flowRate_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(soilMoisture_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, soilMoisture_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(flowRate_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, flowRate_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.project.IrrigationSystemProto.IrrigationSystemRequest)) {
        return super.equals(obj);
      }
      com.project.IrrigationSystemProto.IrrigationSystemRequest other = (com.project.IrrigationSystemProto.IrrigationSystemRequest) obj;

      if (!getSoilMoisture()
          .equals(other.getSoilMoisture())) return false;
      if (!getFlowRate()
          .equals(other.getFlowRate())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SOILMOISTURE_FIELD_NUMBER;
      hash = (53 * hash) + getSoilMoisture().hashCode();
      hash = (37 * hash) + FLOWRATE_FIELD_NUMBER;
      hash = (53 * hash) + getFlowRate().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.project.IrrigationSystemProto.IrrigationSystemRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.project.IrrigationSystemProto.IrrigationSystemRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.project.IrrigationSystemProto.IrrigationSystemRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.project.IrrigationSystemProto.IrrigationSystemRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.project.IrrigationSystemProto.IrrigationSystemRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.project.IrrigationSystemProto.IrrigationSystemRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.project.IrrigationSystemProto.IrrigationSystemRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.project.IrrigationSystemProto.IrrigationSystemRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.project.IrrigationSystemProto.IrrigationSystemRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.project.IrrigationSystemProto.IrrigationSystemRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.project.IrrigationSystemProto.IrrigationSystemRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.project.IrrigationSystemProto.IrrigationSystemRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.project.IrrigationSystemProto.IrrigationSystemRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code IrrigationSystemRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:IrrigationSystemRequest)
        com.project.IrrigationSystemProto.IrrigationSystemRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.project.IrrigationSystemProto.internal_static_IrrigationSystemRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.project.IrrigationSystemProto.internal_static_IrrigationSystemRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.project.IrrigationSystemProto.IrrigationSystemRequest.class, com.project.IrrigationSystemProto.IrrigationSystemRequest.Builder.class);
      }

      // Construct using com.project.IrrigationSystemProto.IrrigationSystemRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        soilMoisture_ = "";
        flowRate_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.project.IrrigationSystemProto.internal_static_IrrigationSystemRequest_descriptor;
      }

      @java.lang.Override
      public com.project.IrrigationSystemProto.IrrigationSystemRequest getDefaultInstanceForType() {
        return com.project.IrrigationSystemProto.IrrigationSystemRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.project.IrrigationSystemProto.IrrigationSystemRequest build() {
        com.project.IrrigationSystemProto.IrrigationSystemRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.project.IrrigationSystemProto.IrrigationSystemRequest buildPartial() {
        com.project.IrrigationSystemProto.IrrigationSystemRequest result = new com.project.IrrigationSystemProto.IrrigationSystemRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.project.IrrigationSystemProto.IrrigationSystemRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.soilMoisture_ = soilMoisture_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.flowRate_ = flowRate_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.project.IrrigationSystemProto.IrrigationSystemRequest) {
          return mergeFrom((com.project.IrrigationSystemProto.IrrigationSystemRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.project.IrrigationSystemProto.IrrigationSystemRequest other) {
        if (other == com.project.IrrigationSystemProto.IrrigationSystemRequest.getDefaultInstance()) return this;
        if (!other.getSoilMoisture().isEmpty()) {
          soilMoisture_ = other.soilMoisture_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getFlowRate().isEmpty()) {
          flowRate_ = other.flowRate_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                soilMoisture_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                flowRate_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object soilMoisture_ = "";
      /**
       * <pre>
       * Soil moisture level: 'Very Low Level', 'Low Level', 'Optimal Level', or 'High Level'.
       * </pre>
       *
       * <code>string soilMoisture = 1;</code>
       * @return The soilMoisture.
       */
      public java.lang.String getSoilMoisture() {
        java.lang.Object ref = soilMoisture_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          soilMoisture_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Soil moisture level: 'Very Low Level', 'Low Level', 'Optimal Level', or 'High Level'.
       * </pre>
       *
       * <code>string soilMoisture = 1;</code>
       * @return The bytes for soilMoisture.
       */
      public com.google.protobuf.ByteString
          getSoilMoistureBytes() {
        java.lang.Object ref = soilMoisture_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          soilMoisture_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Soil moisture level: 'Very Low Level', 'Low Level', 'Optimal Level', or 'High Level'.
       * </pre>
       *
       * <code>string soilMoisture = 1;</code>
       * @param value The soilMoisture to set.
       * @return This builder for chaining.
       */
      public Builder setSoilMoisture(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        soilMoisture_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Soil moisture level: 'Very Low Level', 'Low Level', 'Optimal Level', or 'High Level'.
       * </pre>
       *
       * <code>string soilMoisture = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSoilMoisture() {
        soilMoisture_ = getDefaultInstance().getSoilMoisture();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Soil moisture level: 'Very Low Level', 'Low Level', 'Optimal Level', or 'High Level'.
       * </pre>
       *
       * <code>string soilMoisture = 1;</code>
       * @param value The bytes for soilMoisture to set.
       * @return This builder for chaining.
       */
      public Builder setSoilMoistureBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        soilMoisture_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object flowRate_ = "";
      /**
       * <pre>
       * Water flow rate: 'Low Flow', or 'High Flow'.
       * </pre>
       *
       * <code>string flowRate = 2;</code>
       * @return The flowRate.
       */
      public java.lang.String getFlowRate() {
        java.lang.Object ref = flowRate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          flowRate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Water flow rate: 'Low Flow', or 'High Flow'.
       * </pre>
       *
       * <code>string flowRate = 2;</code>
       * @return The bytes for flowRate.
       */
      public com.google.protobuf.ByteString
          getFlowRateBytes() {
        java.lang.Object ref = flowRate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          flowRate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Water flow rate: 'Low Flow', or 'High Flow'.
       * </pre>
       *
       * <code>string flowRate = 2;</code>
       * @param value The flowRate to set.
       * @return This builder for chaining.
       */
      public Builder setFlowRate(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        flowRate_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Water flow rate: 'Low Flow', or 'High Flow'.
       * </pre>
       *
       * <code>string flowRate = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFlowRate() {
        flowRate_ = getDefaultInstance().getFlowRate();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Water flow rate: 'Low Flow', or 'High Flow'.
       * </pre>
       *
       * <code>string flowRate = 2;</code>
       * @param value The bytes for flowRate to set.
       * @return This builder for chaining.
       */
      public Builder setFlowRateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        flowRate_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:IrrigationSystemRequest)
    }

    // @@protoc_insertion_point(class_scope:IrrigationSystemRequest)
    private static final com.project.IrrigationSystemProto.IrrigationSystemRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.project.IrrigationSystemProto.IrrigationSystemRequest();
    }

    public static com.project.IrrigationSystemProto.IrrigationSystemRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IrrigationSystemRequest>
        PARSER = new com.google.protobuf.AbstractParser<IrrigationSystemRequest>() {
      @java.lang.Override
      public IrrigationSystemRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<IrrigationSystemRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IrrigationSystemRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.project.IrrigationSystemProto.IrrigationSystemRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface IrrigationSystemResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IrrigationSystemResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string instruction = 1;</code>
     * @return The instruction.
     */
    java.lang.String getInstruction();
    /**
     * <code>string instruction = 1;</code>
     * @return The bytes for instruction.
     */
    com.google.protobuf.ByteString
        getInstructionBytes();
  }
  /**
   * Protobuf type {@code IrrigationSystemResponse}
   */
  public static final class IrrigationSystemResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:IrrigationSystemResponse)
      IrrigationSystemResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IrrigationSystemResponse.newBuilder() to construct.
    private IrrigationSystemResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IrrigationSystemResponse() {
      instruction_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new IrrigationSystemResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.project.IrrigationSystemProto.internal_static_IrrigationSystemResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.project.IrrigationSystemProto.internal_static_IrrigationSystemResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.project.IrrigationSystemProto.IrrigationSystemResponse.class, com.project.IrrigationSystemProto.IrrigationSystemResponse.Builder.class);
    }

    public static final int INSTRUCTION_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object instruction_ = "";
    /**
     * <code>string instruction = 1;</code>
     * @return The instruction.
     */
    @java.lang.Override
    public java.lang.String getInstruction() {
      java.lang.Object ref = instruction_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        instruction_ = s;
        return s;
      }
    }
    /**
     * <code>string instruction = 1;</code>
     * @return The bytes for instruction.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getInstructionBytes() {
      java.lang.Object ref = instruction_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        instruction_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(instruction_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, instruction_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(instruction_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, instruction_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.project.IrrigationSystemProto.IrrigationSystemResponse)) {
        return super.equals(obj);
      }
      com.project.IrrigationSystemProto.IrrigationSystemResponse other = (com.project.IrrigationSystemProto.IrrigationSystemResponse) obj;

      if (!getInstruction()
          .equals(other.getInstruction())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INSTRUCTION_FIELD_NUMBER;
      hash = (53 * hash) + getInstruction().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.project.IrrigationSystemProto.IrrigationSystemResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.project.IrrigationSystemProto.IrrigationSystemResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.project.IrrigationSystemProto.IrrigationSystemResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.project.IrrigationSystemProto.IrrigationSystemResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.project.IrrigationSystemProto.IrrigationSystemResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.project.IrrigationSystemProto.IrrigationSystemResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.project.IrrigationSystemProto.IrrigationSystemResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.project.IrrigationSystemProto.IrrigationSystemResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.project.IrrigationSystemProto.IrrigationSystemResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.project.IrrigationSystemProto.IrrigationSystemResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.project.IrrigationSystemProto.IrrigationSystemResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.project.IrrigationSystemProto.IrrigationSystemResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.project.IrrigationSystemProto.IrrigationSystemResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code IrrigationSystemResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:IrrigationSystemResponse)
        com.project.IrrigationSystemProto.IrrigationSystemResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.project.IrrigationSystemProto.internal_static_IrrigationSystemResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.project.IrrigationSystemProto.internal_static_IrrigationSystemResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.project.IrrigationSystemProto.IrrigationSystemResponse.class, com.project.IrrigationSystemProto.IrrigationSystemResponse.Builder.class);
      }

      // Construct using com.project.IrrigationSystemProto.IrrigationSystemResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        instruction_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.project.IrrigationSystemProto.internal_static_IrrigationSystemResponse_descriptor;
      }

      @java.lang.Override
      public com.project.IrrigationSystemProto.IrrigationSystemResponse getDefaultInstanceForType() {
        return com.project.IrrigationSystemProto.IrrigationSystemResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.project.IrrigationSystemProto.IrrigationSystemResponse build() {
        com.project.IrrigationSystemProto.IrrigationSystemResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.project.IrrigationSystemProto.IrrigationSystemResponse buildPartial() {
        com.project.IrrigationSystemProto.IrrigationSystemResponse result = new com.project.IrrigationSystemProto.IrrigationSystemResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.project.IrrigationSystemProto.IrrigationSystemResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.instruction_ = instruction_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.project.IrrigationSystemProto.IrrigationSystemResponse) {
          return mergeFrom((com.project.IrrigationSystemProto.IrrigationSystemResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.project.IrrigationSystemProto.IrrigationSystemResponse other) {
        if (other == com.project.IrrigationSystemProto.IrrigationSystemResponse.getDefaultInstance()) return this;
        if (!other.getInstruction().isEmpty()) {
          instruction_ = other.instruction_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                instruction_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object instruction_ = "";
      /**
       * <code>string instruction = 1;</code>
       * @return The instruction.
       */
      public java.lang.String getInstruction() {
        java.lang.Object ref = instruction_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          instruction_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string instruction = 1;</code>
       * @return The bytes for instruction.
       */
      public com.google.protobuf.ByteString
          getInstructionBytes() {
        java.lang.Object ref = instruction_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          instruction_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string instruction = 1;</code>
       * @param value The instruction to set.
       * @return This builder for chaining.
       */
      public Builder setInstruction(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        instruction_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string instruction = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearInstruction() {
        instruction_ = getDefaultInstance().getInstruction();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string instruction = 1;</code>
       * @param value The bytes for instruction to set.
       * @return This builder for chaining.
       */
      public Builder setInstructionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        instruction_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:IrrigationSystemResponse)
    }

    // @@protoc_insertion_point(class_scope:IrrigationSystemResponse)
    private static final com.project.IrrigationSystemProto.IrrigationSystemResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.project.IrrigationSystemProto.IrrigationSystemResponse();
    }

    public static com.project.IrrigationSystemProto.IrrigationSystemResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IrrigationSystemResponse>
        PARSER = new com.google.protobuf.AbstractParser<IrrigationSystemResponse>() {
      @java.lang.Override
      public IrrigationSystemResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<IrrigationSystemResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IrrigationSystemResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.project.IrrigationSystemProto.IrrigationSystemResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IrrigationSystemRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IrrigationSystemRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IrrigationSystemResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IrrigationSystemResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026IrrigationSystem.proto\"A\n\027IrrigationSy" +
      "stemRequest\022\024\n\014soilMoisture\030\001 \001(\t\022\020\n\010flo" +
      "wRate\030\002 \001(\t\"/\n\030IrrigationSystemResponse\022" +
      "\023\n\013instruction\030\001 \001(\t2h\n\027IrrigationSystem" +
      "Service\022M\n\020irrigationSystem\022\030.Irrigation" +
      "SystemRequest\032\031.IrrigationSystemResponse" +
      "\"\000(\0010\001B&\n\013com.projectB\025IrrigationSystemP" +
      "rotoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_IrrigationSystemRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_IrrigationSystemRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IrrigationSystemRequest_descriptor,
        new java.lang.String[] { "SoilMoisture", "FlowRate", });
    internal_static_IrrigationSystemResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_IrrigationSystemResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IrrigationSystemResponse_descriptor,
        new java.lang.String[] { "Instruction", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
