// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: soilSensor.proto

// Protobuf Java Version: 3.25.1
package com.project;

public final class SoilSensorProto {
  private SoilSensorProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SoilInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SoilInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 moistureLevel = 1;</code>
     * @return The moistureLevel.
     */
    int getMoistureLevel();

    /**
     * <code>int32 phLevel = 2;</code>
     * @return The phLevel.
     */
    int getPhLevel();

    /**
     * <code>int32 soilTemperature = 3;</code>
     * @return The soilTemperature.
     */
    int getSoilTemperature();
  }
  /**
   * Protobuf type {@code SoilInfo}
   */
  public static final class SoilInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SoilInfo)
      SoilInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SoilInfo.newBuilder() to construct.
    private SoilInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SoilInfo() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SoilInfo();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.project.SoilSensorProto.internal_static_SoilInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.project.SoilSensorProto.internal_static_SoilInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.project.SoilSensorProto.SoilInfo.class, com.project.SoilSensorProto.SoilInfo.Builder.class);
    }

    public static final int MOISTURELEVEL_FIELD_NUMBER = 1;
    private int moistureLevel_ = 0;
    /**
     * <code>int32 moistureLevel = 1;</code>
     * @return The moistureLevel.
     */
    @java.lang.Override
    public int getMoistureLevel() {
      return moistureLevel_;
    }

    public static final int PHLEVEL_FIELD_NUMBER = 2;
    private int phLevel_ = 0;
    /**
     * <code>int32 phLevel = 2;</code>
     * @return The phLevel.
     */
    @java.lang.Override
    public int getPhLevel() {
      return phLevel_;
    }

    public static final int SOILTEMPERATURE_FIELD_NUMBER = 3;
    private int soilTemperature_ = 0;
    /**
     * <code>int32 soilTemperature = 3;</code>
     * @return The soilTemperature.
     */
    @java.lang.Override
    public int getSoilTemperature() {
      return soilTemperature_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (moistureLevel_ != 0) {
        output.writeInt32(1, moistureLevel_);
      }
      if (phLevel_ != 0) {
        output.writeInt32(2, phLevel_);
      }
      if (soilTemperature_ != 0) {
        output.writeInt32(3, soilTemperature_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (moistureLevel_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, moistureLevel_);
      }
      if (phLevel_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, phLevel_);
      }
      if (soilTemperature_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, soilTemperature_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.project.SoilSensorProto.SoilInfo)) {
        return super.equals(obj);
      }
      com.project.SoilSensorProto.SoilInfo other = (com.project.SoilSensorProto.SoilInfo) obj;

      if (getMoistureLevel()
          != other.getMoistureLevel()) return false;
      if (getPhLevel()
          != other.getPhLevel()) return false;
      if (getSoilTemperature()
          != other.getSoilTemperature()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MOISTURELEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getMoistureLevel();
      hash = (37 * hash) + PHLEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getPhLevel();
      hash = (37 * hash) + SOILTEMPERATURE_FIELD_NUMBER;
      hash = (53 * hash) + getSoilTemperature();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.project.SoilSensorProto.SoilInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.project.SoilSensorProto.SoilInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.project.SoilSensorProto.SoilInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.project.SoilSensorProto.SoilInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.project.SoilSensorProto.SoilInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.project.SoilSensorProto.SoilInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.project.SoilSensorProto.SoilInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.project.SoilSensorProto.SoilInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.project.SoilSensorProto.SoilInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.project.SoilSensorProto.SoilInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.project.SoilSensorProto.SoilInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.project.SoilSensorProto.SoilInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.project.SoilSensorProto.SoilInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SoilInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SoilInfo)
        com.project.SoilSensorProto.SoilInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.project.SoilSensorProto.internal_static_SoilInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.project.SoilSensorProto.internal_static_SoilInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.project.SoilSensorProto.SoilInfo.class, com.project.SoilSensorProto.SoilInfo.Builder.class);
      }

      // Construct using com.project.SoilSensorProto.SoilInfo.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        moistureLevel_ = 0;
        phLevel_ = 0;
        soilTemperature_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.project.SoilSensorProto.internal_static_SoilInfo_descriptor;
      }

      @java.lang.Override
      public com.project.SoilSensorProto.SoilInfo getDefaultInstanceForType() {
        return com.project.SoilSensorProto.SoilInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.project.SoilSensorProto.SoilInfo build() {
        com.project.SoilSensorProto.SoilInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.project.SoilSensorProto.SoilInfo buildPartial() {
        com.project.SoilSensorProto.SoilInfo result = new com.project.SoilSensorProto.SoilInfo(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.project.SoilSensorProto.SoilInfo result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.moistureLevel_ = moistureLevel_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.phLevel_ = phLevel_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.soilTemperature_ = soilTemperature_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.project.SoilSensorProto.SoilInfo) {
          return mergeFrom((com.project.SoilSensorProto.SoilInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.project.SoilSensorProto.SoilInfo other) {
        if (other == com.project.SoilSensorProto.SoilInfo.getDefaultInstance()) return this;
        if (other.getMoistureLevel() != 0) {
          setMoistureLevel(other.getMoistureLevel());
        }
        if (other.getPhLevel() != 0) {
          setPhLevel(other.getPhLevel());
        }
        if (other.getSoilTemperature() != 0) {
          setSoilTemperature(other.getSoilTemperature());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                moistureLevel_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                phLevel_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                soilTemperature_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int moistureLevel_ ;
      /**
       * <code>int32 moistureLevel = 1;</code>
       * @return The moistureLevel.
       */
      @java.lang.Override
      public int getMoistureLevel() {
        return moistureLevel_;
      }
      /**
       * <code>int32 moistureLevel = 1;</code>
       * @param value The moistureLevel to set.
       * @return This builder for chaining.
       */
      public Builder setMoistureLevel(int value) {

        moistureLevel_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 moistureLevel = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMoistureLevel() {
        bitField0_ = (bitField0_ & ~0x00000001);
        moistureLevel_ = 0;
        onChanged();
        return this;
      }

      private int phLevel_ ;
      /**
       * <code>int32 phLevel = 2;</code>
       * @return The phLevel.
       */
      @java.lang.Override
      public int getPhLevel() {
        return phLevel_;
      }
      /**
       * <code>int32 phLevel = 2;</code>
       * @param value The phLevel to set.
       * @return This builder for chaining.
       */
      public Builder setPhLevel(int value) {

        phLevel_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 phLevel = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPhLevel() {
        bitField0_ = (bitField0_ & ~0x00000002);
        phLevel_ = 0;
        onChanged();
        return this;
      }

      private int soilTemperature_ ;
      /**
       * <code>int32 soilTemperature = 3;</code>
       * @return The soilTemperature.
       */
      @java.lang.Override
      public int getSoilTemperature() {
        return soilTemperature_;
      }
      /**
       * <code>int32 soilTemperature = 3;</code>
       * @param value The soilTemperature to set.
       * @return This builder for chaining.
       */
      public Builder setSoilTemperature(int value) {

        soilTemperature_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 soilTemperature = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSoilTemperature() {
        bitField0_ = (bitField0_ & ~0x00000004);
        soilTemperature_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SoilInfo)
    }

    // @@protoc_insertion_point(class_scope:SoilInfo)
    private static final com.project.SoilSensorProto.SoilInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.project.SoilSensorProto.SoilInfo();
    }

    public static com.project.SoilSensorProto.SoilInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SoilInfo>
        PARSER = new com.google.protobuf.AbstractParser<SoilInfo>() {
      @java.lang.Override
      public SoilInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SoilInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SoilInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.project.SoilSensorProto.SoilInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SoilInfoSummaryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SoilInfoSummary)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * the number of SoilInfo messages received
     * </pre>
     *
     * <code>int32 requestCount = 1;</code>
     * @return The requestCount.
     */
    int getRequestCount();

    /**
     * <code>double averageMoistureLevel = 2;</code>
     * @return The averageMoistureLevel.
     */
    double getAverageMoistureLevel();

    /**
     * <code>double averagePHLevel = 3;</code>
     * @return The averagePHLevel.
     */
    double getAveragePHLevel();

    /**
     * <code>double averageSoilTemperature = 4;</code>
     * @return The averageSoilTemperature.
     */
    double getAverageSoilTemperature();
  }
  /**
   * Protobuf type {@code SoilInfoSummary}
   */
  public static final class SoilInfoSummary extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SoilInfoSummary)
      SoilInfoSummaryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SoilInfoSummary.newBuilder() to construct.
    private SoilInfoSummary(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SoilInfoSummary() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SoilInfoSummary();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.project.SoilSensorProto.internal_static_SoilInfoSummary_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.project.SoilSensorProto.internal_static_SoilInfoSummary_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.project.SoilSensorProto.SoilInfoSummary.class, com.project.SoilSensorProto.SoilInfoSummary.Builder.class);
    }

    public static final int REQUESTCOUNT_FIELD_NUMBER = 1;
    private int requestCount_ = 0;
    /**
     * <pre>
     * the number of SoilInfo messages received
     * </pre>
     *
     * <code>int32 requestCount = 1;</code>
     * @return The requestCount.
     */
    @java.lang.Override
    public int getRequestCount() {
      return requestCount_;
    }

    public static final int AVERAGEMOISTURELEVEL_FIELD_NUMBER = 2;
    private double averageMoistureLevel_ = 0D;
    /**
     * <code>double averageMoistureLevel = 2;</code>
     * @return The averageMoistureLevel.
     */
    @java.lang.Override
    public double getAverageMoistureLevel() {
      return averageMoistureLevel_;
    }

    public static final int AVERAGEPHLEVEL_FIELD_NUMBER = 3;
    private double averagePHLevel_ = 0D;
    /**
     * <code>double averagePHLevel = 3;</code>
     * @return The averagePHLevel.
     */
    @java.lang.Override
    public double getAveragePHLevel() {
      return averagePHLevel_;
    }

    public static final int AVERAGESOILTEMPERATURE_FIELD_NUMBER = 4;
    private double averageSoilTemperature_ = 0D;
    /**
     * <code>double averageSoilTemperature = 4;</code>
     * @return The averageSoilTemperature.
     */
    @java.lang.Override
    public double getAverageSoilTemperature() {
      return averageSoilTemperature_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (requestCount_ != 0) {
        output.writeInt32(1, requestCount_);
      }
      if (java.lang.Double.doubleToRawLongBits(averageMoistureLevel_) != 0) {
        output.writeDouble(2, averageMoistureLevel_);
      }
      if (java.lang.Double.doubleToRawLongBits(averagePHLevel_) != 0) {
        output.writeDouble(3, averagePHLevel_);
      }
      if (java.lang.Double.doubleToRawLongBits(averageSoilTemperature_) != 0) {
        output.writeDouble(4, averageSoilTemperature_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (requestCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, requestCount_);
      }
      if (java.lang.Double.doubleToRawLongBits(averageMoistureLevel_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, averageMoistureLevel_);
      }
      if (java.lang.Double.doubleToRawLongBits(averagePHLevel_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, averagePHLevel_);
      }
      if (java.lang.Double.doubleToRawLongBits(averageSoilTemperature_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, averageSoilTemperature_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.project.SoilSensorProto.SoilInfoSummary)) {
        return super.equals(obj);
      }
      com.project.SoilSensorProto.SoilInfoSummary other = (com.project.SoilSensorProto.SoilInfoSummary) obj;

      if (getRequestCount()
          != other.getRequestCount()) return false;
      if (java.lang.Double.doubleToLongBits(getAverageMoistureLevel())
          != java.lang.Double.doubleToLongBits(
              other.getAverageMoistureLevel())) return false;
      if (java.lang.Double.doubleToLongBits(getAveragePHLevel())
          != java.lang.Double.doubleToLongBits(
              other.getAveragePHLevel())) return false;
      if (java.lang.Double.doubleToLongBits(getAverageSoilTemperature())
          != java.lang.Double.doubleToLongBits(
              other.getAverageSoilTemperature())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUESTCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getRequestCount();
      hash = (37 * hash) + AVERAGEMOISTURELEVEL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAverageMoistureLevel()));
      hash = (37 * hash) + AVERAGEPHLEVEL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAveragePHLevel()));
      hash = (37 * hash) + AVERAGESOILTEMPERATURE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAverageSoilTemperature()));
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.project.SoilSensorProto.SoilInfoSummary parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.project.SoilSensorProto.SoilInfoSummary parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.project.SoilSensorProto.SoilInfoSummary parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.project.SoilSensorProto.SoilInfoSummary parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.project.SoilSensorProto.SoilInfoSummary parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.project.SoilSensorProto.SoilInfoSummary parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.project.SoilSensorProto.SoilInfoSummary parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.project.SoilSensorProto.SoilInfoSummary parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.project.SoilSensorProto.SoilInfoSummary parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.project.SoilSensorProto.SoilInfoSummary parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.project.SoilSensorProto.SoilInfoSummary parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.project.SoilSensorProto.SoilInfoSummary parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.project.SoilSensorProto.SoilInfoSummary prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SoilInfoSummary}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SoilInfoSummary)
        com.project.SoilSensorProto.SoilInfoSummaryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.project.SoilSensorProto.internal_static_SoilInfoSummary_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.project.SoilSensorProto.internal_static_SoilInfoSummary_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.project.SoilSensorProto.SoilInfoSummary.class, com.project.SoilSensorProto.SoilInfoSummary.Builder.class);
      }

      // Construct using com.project.SoilSensorProto.SoilInfoSummary.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        requestCount_ = 0;
        averageMoistureLevel_ = 0D;
        averagePHLevel_ = 0D;
        averageSoilTemperature_ = 0D;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.project.SoilSensorProto.internal_static_SoilInfoSummary_descriptor;
      }

      @java.lang.Override
      public com.project.SoilSensorProto.SoilInfoSummary getDefaultInstanceForType() {
        return com.project.SoilSensorProto.SoilInfoSummary.getDefaultInstance();
      }

      @java.lang.Override
      public com.project.SoilSensorProto.SoilInfoSummary build() {
        com.project.SoilSensorProto.SoilInfoSummary result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.project.SoilSensorProto.SoilInfoSummary buildPartial() {
        com.project.SoilSensorProto.SoilInfoSummary result = new com.project.SoilSensorProto.SoilInfoSummary(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.project.SoilSensorProto.SoilInfoSummary result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.requestCount_ = requestCount_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.averageMoistureLevel_ = averageMoistureLevel_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.averagePHLevel_ = averagePHLevel_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.averageSoilTemperature_ = averageSoilTemperature_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.project.SoilSensorProto.SoilInfoSummary) {
          return mergeFrom((com.project.SoilSensorProto.SoilInfoSummary)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.project.SoilSensorProto.SoilInfoSummary other) {
        if (other == com.project.SoilSensorProto.SoilInfoSummary.getDefaultInstance()) return this;
        if (other.getRequestCount() != 0) {
          setRequestCount(other.getRequestCount());
        }
        if (other.getAverageMoistureLevel() != 0D) {
          setAverageMoistureLevel(other.getAverageMoistureLevel());
        }
        if (other.getAveragePHLevel() != 0D) {
          setAveragePHLevel(other.getAveragePHLevel());
        }
        if (other.getAverageSoilTemperature() != 0D) {
          setAverageSoilTemperature(other.getAverageSoilTemperature());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                requestCount_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 17: {
                averageMoistureLevel_ = input.readDouble();
                bitField0_ |= 0x00000002;
                break;
              } // case 17
              case 25: {
                averagePHLevel_ = input.readDouble();
                bitField0_ |= 0x00000004;
                break;
              } // case 25
              case 33: {
                averageSoilTemperature_ = input.readDouble();
                bitField0_ |= 0x00000008;
                break;
              } // case 33
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int requestCount_ ;
      /**
       * <pre>
       * the number of SoilInfo messages received
       * </pre>
       *
       * <code>int32 requestCount = 1;</code>
       * @return The requestCount.
       */
      @java.lang.Override
      public int getRequestCount() {
        return requestCount_;
      }
      /**
       * <pre>
       * the number of SoilInfo messages received
       * </pre>
       *
       * <code>int32 requestCount = 1;</code>
       * @param value The requestCount to set.
       * @return This builder for chaining.
       */
      public Builder setRequestCount(int value) {

        requestCount_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the number of SoilInfo messages received
       * </pre>
       *
       * <code>int32 requestCount = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestCount() {
        bitField0_ = (bitField0_ & ~0x00000001);
        requestCount_ = 0;
        onChanged();
        return this;
      }

      private double averageMoistureLevel_ ;
      /**
       * <code>double averageMoistureLevel = 2;</code>
       * @return The averageMoistureLevel.
       */
      @java.lang.Override
      public double getAverageMoistureLevel() {
        return averageMoistureLevel_;
      }
      /**
       * <code>double averageMoistureLevel = 2;</code>
       * @param value The averageMoistureLevel to set.
       * @return This builder for chaining.
       */
      public Builder setAverageMoistureLevel(double value) {

        averageMoistureLevel_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>double averageMoistureLevel = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAverageMoistureLevel() {
        bitField0_ = (bitField0_ & ~0x00000002);
        averageMoistureLevel_ = 0D;
        onChanged();
        return this;
      }

      private double averagePHLevel_ ;
      /**
       * <code>double averagePHLevel = 3;</code>
       * @return The averagePHLevel.
       */
      @java.lang.Override
      public double getAveragePHLevel() {
        return averagePHLevel_;
      }
      /**
       * <code>double averagePHLevel = 3;</code>
       * @param value The averagePHLevel to set.
       * @return This builder for chaining.
       */
      public Builder setAveragePHLevel(double value) {

        averagePHLevel_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>double averagePHLevel = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAveragePHLevel() {
        bitField0_ = (bitField0_ & ~0x00000004);
        averagePHLevel_ = 0D;
        onChanged();
        return this;
      }

      private double averageSoilTemperature_ ;
      /**
       * <code>double averageSoilTemperature = 4;</code>
       * @return The averageSoilTemperature.
       */
      @java.lang.Override
      public double getAverageSoilTemperature() {
        return averageSoilTemperature_;
      }
      /**
       * <code>double averageSoilTemperature = 4;</code>
       * @param value The averageSoilTemperature to set.
       * @return This builder for chaining.
       */
      public Builder setAverageSoilTemperature(double value) {

        averageSoilTemperature_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>double averageSoilTemperature = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAverageSoilTemperature() {
        bitField0_ = (bitField0_ & ~0x00000008);
        averageSoilTemperature_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SoilInfoSummary)
    }

    // @@protoc_insertion_point(class_scope:SoilInfoSummary)
    private static final com.project.SoilSensorProto.SoilInfoSummary DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.project.SoilSensorProto.SoilInfoSummary();
    }

    public static com.project.SoilSensorProto.SoilInfoSummary getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SoilInfoSummary>
        PARSER = new com.google.protobuf.AbstractParser<SoilInfoSummary>() {
      @java.lang.Override
      public SoilInfoSummary parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SoilInfoSummary> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SoilInfoSummary> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.project.SoilSensorProto.SoilInfoSummary getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SoilInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SoilInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SoilInfoSummary_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SoilInfoSummary_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020soilSensor.proto\"K\n\010SoilInfo\022\025\n\rmoistu" +
      "reLevel\030\001 \001(\005\022\017\n\007phLevel\030\002 \001(\005\022\027\n\017soilTe" +
      "mperature\030\003 \001(\005\"}\n\017SoilInfoSummary\022\024\n\014re" +
      "questCount\030\001 \001(\005\022\034\n\024averageMoistureLevel" +
      "\030\002 \001(\001\022\026\n\016averagePHLevel\030\003 \001(\001\022\036\n\026averag" +
      "eSoilTemperature\030\004 \001(\0012D\n\021SoilSensorServ" +
      "ice\022/\n\014SendSoilInfo\022\t.SoilInfo\032\020.SoilInf" +
      "oSummary\"\000(\001B \n\013com.projectB\017SoilSensorP" +
      "rotoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_SoilInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SoilInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SoilInfo_descriptor,
        new java.lang.String[] { "MoistureLevel", "PhLevel", "SoilTemperature", });
    internal_static_SoilInfoSummary_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SoilInfoSummary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SoilInfoSummary_descriptor,
        new java.lang.String[] { "RequestCount", "AverageMoistureLevel", "AveragePHLevel", "AverageSoilTemperature", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
