// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: soilSensor.proto

// Protobuf Java Version: 3.25.1
package com.project;

public final class SoilSensorProto {
  private SoilSensorProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SoilSensorRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SoilSensorRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * messages about temperature, nutrition, and pHLevel
     * </pre>
     *
     * <code>string soilInfo = 1;</code>
     * @return The soilInfo.
     */
    java.lang.String getSoilInfo();
    /**
     * <pre>
     * messages about temperature, nutrition, and pHLevel
     * </pre>
     *
     * <code>string soilInfo = 1;</code>
     * @return The bytes for soilInfo.
     */
    com.google.protobuf.ByteString
        getSoilInfoBytes();
  }
  /**
   * Protobuf type {@code SoilSensorRequest}
   */
  public static final class SoilSensorRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SoilSensorRequest)
      SoilSensorRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SoilSensorRequest.newBuilder() to construct.
    private SoilSensorRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SoilSensorRequest() {
      soilInfo_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SoilSensorRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.project.SoilSensorProto.internal_static_SoilSensorRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.project.SoilSensorProto.internal_static_SoilSensorRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.project.SoilSensorProto.SoilSensorRequest.class, com.project.SoilSensorProto.SoilSensorRequest.Builder.class);
    }

    public static final int SOILINFO_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object soilInfo_ = "";
    /**
     * <pre>
     * messages about temperature, nutrition, and pHLevel
     * </pre>
     *
     * <code>string soilInfo = 1;</code>
     * @return The soilInfo.
     */
    @java.lang.Override
    public java.lang.String getSoilInfo() {
      java.lang.Object ref = soilInfo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        soilInfo_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * messages about temperature, nutrition, and pHLevel
     * </pre>
     *
     * <code>string soilInfo = 1;</code>
     * @return The bytes for soilInfo.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSoilInfoBytes() {
      java.lang.Object ref = soilInfo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        soilInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(soilInfo_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, soilInfo_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(soilInfo_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, soilInfo_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.project.SoilSensorProto.SoilSensorRequest)) {
        return super.equals(obj);
      }
      com.project.SoilSensorProto.SoilSensorRequest other = (com.project.SoilSensorProto.SoilSensorRequest) obj;

      if (!getSoilInfo()
          .equals(other.getSoilInfo())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SOILINFO_FIELD_NUMBER;
      hash = (53 * hash) + getSoilInfo().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.project.SoilSensorProto.SoilSensorRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.project.SoilSensorProto.SoilSensorRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.project.SoilSensorProto.SoilSensorRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.project.SoilSensorProto.SoilSensorRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.project.SoilSensorProto.SoilSensorRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.project.SoilSensorProto.SoilSensorRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.project.SoilSensorProto.SoilSensorRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.project.SoilSensorProto.SoilSensorRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.project.SoilSensorProto.SoilSensorRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.project.SoilSensorProto.SoilSensorRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.project.SoilSensorProto.SoilSensorRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.project.SoilSensorProto.SoilSensorRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.project.SoilSensorProto.SoilSensorRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SoilSensorRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SoilSensorRequest)
        com.project.SoilSensorProto.SoilSensorRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.project.SoilSensorProto.internal_static_SoilSensorRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.project.SoilSensorProto.internal_static_SoilSensorRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.project.SoilSensorProto.SoilSensorRequest.class, com.project.SoilSensorProto.SoilSensorRequest.Builder.class);
      }

      // Construct using com.project.SoilSensorProto.SoilSensorRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        soilInfo_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.project.SoilSensorProto.internal_static_SoilSensorRequest_descriptor;
      }

      @java.lang.Override
      public com.project.SoilSensorProto.SoilSensorRequest getDefaultInstanceForType() {
        return com.project.SoilSensorProto.SoilSensorRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.project.SoilSensorProto.SoilSensorRequest build() {
        com.project.SoilSensorProto.SoilSensorRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.project.SoilSensorProto.SoilSensorRequest buildPartial() {
        com.project.SoilSensorProto.SoilSensorRequest result = new com.project.SoilSensorProto.SoilSensorRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.project.SoilSensorProto.SoilSensorRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.soilInfo_ = soilInfo_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.project.SoilSensorProto.SoilSensorRequest) {
          return mergeFrom((com.project.SoilSensorProto.SoilSensorRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.project.SoilSensorProto.SoilSensorRequest other) {
        if (other == com.project.SoilSensorProto.SoilSensorRequest.getDefaultInstance()) return this;
        if (!other.getSoilInfo().isEmpty()) {
          soilInfo_ = other.soilInfo_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                soilInfo_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object soilInfo_ = "";
      /**
       * <pre>
       * messages about temperature, nutrition, and pHLevel
       * </pre>
       *
       * <code>string soilInfo = 1;</code>
       * @return The soilInfo.
       */
      public java.lang.String getSoilInfo() {
        java.lang.Object ref = soilInfo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          soilInfo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * messages about temperature, nutrition, and pHLevel
       * </pre>
       *
       * <code>string soilInfo = 1;</code>
       * @return The bytes for soilInfo.
       */
      public com.google.protobuf.ByteString
          getSoilInfoBytes() {
        java.lang.Object ref = soilInfo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          soilInfo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * messages about temperature, nutrition, and pHLevel
       * </pre>
       *
       * <code>string soilInfo = 1;</code>
       * @param value The soilInfo to set.
       * @return This builder for chaining.
       */
      public Builder setSoilInfo(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        soilInfo_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * messages about temperature, nutrition, and pHLevel
       * </pre>
       *
       * <code>string soilInfo = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSoilInfo() {
        soilInfo_ = getDefaultInstance().getSoilInfo();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * messages about temperature, nutrition, and pHLevel
       * </pre>
       *
       * <code>string soilInfo = 1;</code>
       * @param value The bytes for soilInfo to set.
       * @return This builder for chaining.
       */
      public Builder setSoilInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        soilInfo_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SoilSensorRequest)
    }

    // @@protoc_insertion_point(class_scope:SoilSensorRequest)
    private static final com.project.SoilSensorProto.SoilSensorRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.project.SoilSensorProto.SoilSensorRequest();
    }

    public static com.project.SoilSensorProto.SoilSensorRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SoilSensorRequest>
        PARSER = new com.google.protobuf.AbstractParser<SoilSensorRequest>() {
      @java.lang.Override
      public SoilSensorRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SoilSensorRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SoilSensorRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.project.SoilSensorProto.SoilSensorRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SoilSensorResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SoilSensorResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * receive confirmation
     * </pre>
     *
     * <code>string serverMessage = 1;</code>
     * @return The serverMessage.
     */
    java.lang.String getServerMessage();
    /**
     * <pre>
     * receive confirmation
     * </pre>
     *
     * <code>string serverMessage = 1;</code>
     * @return The bytes for serverMessage.
     */
    com.google.protobuf.ByteString
        getServerMessageBytes();
  }
  /**
   * Protobuf type {@code SoilSensorResponse}
   */
  public static final class SoilSensorResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SoilSensorResponse)
      SoilSensorResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SoilSensorResponse.newBuilder() to construct.
    private SoilSensorResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SoilSensorResponse() {
      serverMessage_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SoilSensorResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.project.SoilSensorProto.internal_static_SoilSensorResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.project.SoilSensorProto.internal_static_SoilSensorResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.project.SoilSensorProto.SoilSensorResponse.class, com.project.SoilSensorProto.SoilSensorResponse.Builder.class);
    }

    public static final int SERVERMESSAGE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object serverMessage_ = "";
    /**
     * <pre>
     * receive confirmation
     * </pre>
     *
     * <code>string serverMessage = 1;</code>
     * @return The serverMessage.
     */
    @java.lang.Override
    public java.lang.String getServerMessage() {
      java.lang.Object ref = serverMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serverMessage_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * receive confirmation
     * </pre>
     *
     * <code>string serverMessage = 1;</code>
     * @return The bytes for serverMessage.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getServerMessageBytes() {
      java.lang.Object ref = serverMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serverMessage_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, serverMessage_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serverMessage_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, serverMessage_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.project.SoilSensorProto.SoilSensorResponse)) {
        return super.equals(obj);
      }
      com.project.SoilSensorProto.SoilSensorResponse other = (com.project.SoilSensorProto.SoilSensorResponse) obj;

      if (!getServerMessage()
          .equals(other.getServerMessage())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SERVERMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getServerMessage().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.project.SoilSensorProto.SoilSensorResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.project.SoilSensorProto.SoilSensorResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.project.SoilSensorProto.SoilSensorResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.project.SoilSensorProto.SoilSensorResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.project.SoilSensorProto.SoilSensorResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.project.SoilSensorProto.SoilSensorResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.project.SoilSensorProto.SoilSensorResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.project.SoilSensorProto.SoilSensorResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.project.SoilSensorProto.SoilSensorResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.project.SoilSensorProto.SoilSensorResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.project.SoilSensorProto.SoilSensorResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.project.SoilSensorProto.SoilSensorResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.project.SoilSensorProto.SoilSensorResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SoilSensorResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SoilSensorResponse)
        com.project.SoilSensorProto.SoilSensorResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.project.SoilSensorProto.internal_static_SoilSensorResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.project.SoilSensorProto.internal_static_SoilSensorResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.project.SoilSensorProto.SoilSensorResponse.class, com.project.SoilSensorProto.SoilSensorResponse.Builder.class);
      }

      // Construct using com.project.SoilSensorProto.SoilSensorResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        serverMessage_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.project.SoilSensorProto.internal_static_SoilSensorResponse_descriptor;
      }

      @java.lang.Override
      public com.project.SoilSensorProto.SoilSensorResponse getDefaultInstanceForType() {
        return com.project.SoilSensorProto.SoilSensorResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.project.SoilSensorProto.SoilSensorResponse build() {
        com.project.SoilSensorProto.SoilSensorResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.project.SoilSensorProto.SoilSensorResponse buildPartial() {
        com.project.SoilSensorProto.SoilSensorResponse result = new com.project.SoilSensorProto.SoilSensorResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.project.SoilSensorProto.SoilSensorResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.serverMessage_ = serverMessage_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.project.SoilSensorProto.SoilSensorResponse) {
          return mergeFrom((com.project.SoilSensorProto.SoilSensorResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.project.SoilSensorProto.SoilSensorResponse other) {
        if (other == com.project.SoilSensorProto.SoilSensorResponse.getDefaultInstance()) return this;
        if (!other.getServerMessage().isEmpty()) {
          serverMessage_ = other.serverMessage_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                serverMessage_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object serverMessage_ = "";
      /**
       * <pre>
       * receive confirmation
       * </pre>
       *
       * <code>string serverMessage = 1;</code>
       * @return The serverMessage.
       */
      public java.lang.String getServerMessage() {
        java.lang.Object ref = serverMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          serverMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * receive confirmation
       * </pre>
       *
       * <code>string serverMessage = 1;</code>
       * @return The bytes for serverMessage.
       */
      public com.google.protobuf.ByteString
          getServerMessageBytes() {
        java.lang.Object ref = serverMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serverMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * receive confirmation
       * </pre>
       *
       * <code>string serverMessage = 1;</code>
       * @param value The serverMessage to set.
       * @return This builder for chaining.
       */
      public Builder setServerMessage(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        serverMessage_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * receive confirmation
       * </pre>
       *
       * <code>string serverMessage = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearServerMessage() {
        serverMessage_ = getDefaultInstance().getServerMessage();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * receive confirmation
       * </pre>
       *
       * <code>string serverMessage = 1;</code>
       * @param value The bytes for serverMessage to set.
       * @return This builder for chaining.
       */
      public Builder setServerMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        serverMessage_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SoilSensorResponse)
    }

    // @@protoc_insertion_point(class_scope:SoilSensorResponse)
    private static final com.project.SoilSensorProto.SoilSensorResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.project.SoilSensorProto.SoilSensorResponse();
    }

    public static com.project.SoilSensorProto.SoilSensorResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SoilSensorResponse>
        PARSER = new com.google.protobuf.AbstractParser<SoilSensorResponse>() {
      @java.lang.Override
      public SoilSensorResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SoilSensorResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SoilSensorResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.project.SoilSensorProto.SoilSensorResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SoilSensorRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SoilSensorRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SoilSensorResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SoilSensorResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020soilSensor.proto\"%\n\021SoilSensorRequest\022" +
      "\020\n\010soilInfo\030\001 \001(\t\"+\n\022SoilSensorResponse\022" +
      "\025\n\rserverMessage\030\001 \001(\t2N\n\021SoilSensorServ" +
      "ice\0229\n\nsoilSensor\022\022.SoilSensorRequest\032\023." +
      "SoilSensorResponse\"\000(\001B \n\013com.projectB\017S" +
      "oilSensorProtoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_SoilSensorRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SoilSensorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SoilSensorRequest_descriptor,
        new java.lang.String[] { "SoilInfo", });
    internal_static_SoilSensorResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SoilSensorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SoilSensorResponse_descriptor,
        new java.lang.String[] { "ServerMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
